### ISSUE TITLE
Great library, ready for use?

### ISSUE THREAD

**Issue by ddibiase** [jnordberg/wsrpc#1]
Hi there,

Looking to use wsprc in production, wondering how stable it is and if it's fully baked?

Aside from that I'm wondering if this is a standard implementation. We're going to be interfacing an iOS application to consume the RPC calls, would we require a special client to do that or would any ProtoBuf WS RPC library work?

Thanks.

**Comment by jnordberg** [comment]
Hey! Yeah it's ready for use, I've been running it in production for a couple of months now with no problems.

To interface with iOS you would need to implement this protocol: https://github.com/jnordberg/wsrpc/blob/master/protocol/rpc.proto

But if you don't need the low latency and browser support that wsrpc provides I suggest you check out http://grpc.io which has a lot more weight behind it than this project :) I think it has a iOS client library as well.
