### ISSUE TITLE
uws deprecated

### ISSUE THREAD

**Issue by WarL0ckNet** [jnordberg/wsrpc#4]
Hi

> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'uws'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/sites/ms/node_modules/wsrpc/lib6/server.js:46:19)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)

**Comment by jnordberg** [comment]
Thanks for the notice, uWebSocket and its maintainer has always been a pain to deal with... I've swapped over to using the `ws` package instead and published as 1.4.0

**Comment by pranaypratyush** [comment]
Possible to provide uws as an option?
