### ISSUE TITLE
Unplanned error in tests

### ISSUE THREAD

**Issue by tbence94** [jnordberg/wsrpc#5]
Should I worry about this new unplanned error?
https://travis-ci.org/jnordberg/wsrpc/jobs/602023963#L321

---

What do you think about a failing the tests when an unplanned error happens?

Implementation idea:
Set a flag in the error handlers where you log these unplanned errors and create a new test at the end which checks if any unplanned error happend.

**Comment by tbence94** [comment]
**UPDATE:**

Changing this `plannedError` to `true` solves the issue:
https://github.com/jnordberg/wsrpc/blob/master/test/index.ts#L213

This is the change what caused the new error:
https://github.com/jnordberg/wsrpc/blob/master/src/server.ts#L294

**Comment by jnordberg** [comment]
I wouldn't worry about it, just a behavioral difference between `ws` and `uws` package. We should plan for this error and adding a test failure on unplanned error events is a good idea

**Comment by tbence94** [comment]
Implemented proposed changes in this PR: https://github.com/jnordberg/wsrpc/pull/6
